# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waftester < Formula
  desc "WAF security testing CLI — detect, benchmark, and bypass web application firewalls"
  homepage "https://waftester.com"
  version "2.9.23"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waftester/waftester/releases/download/v2.9.23/waftester_Darwin_x86_64.tar.gz"
      sha256 "900de82ceb4f5cdabe15e664caa6b0a2506afa2d5b32838f544851307d203ff8"

      def install
        bin.install "waf-tester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waftester/waftester/releases/download/v2.9.23/waftester_Darwin_arm64.tar.gz"
      sha256 "6d31b44e0d7490b31a7178bdb53ea96d08649e3523596c17c938c6dd21099ec4"

      def install
        bin.install "waf-tester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/waftester/waftester/releases/download/v2.9.23/waftester_Linux_x86_64.tar.gz"
      sha256 "1e70a04cd6d1b264bd461b9cb59da8380ee830309e2f45b0bb66a530eea87735"
      def install
        bin.install "waf-tester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/waftester/waftester/releases/download/v2.9.23/waftester_Linux_arm64.tar.gz"
      sha256 "a47592245b6de84218c619d404de26c3c55d446d1c13c6b8b59cc66445df9fab"
      def install
        bin.install "waf-tester"
      end
    end
  end

  test do
    system "#{bin}/waf-tester", "version"
  end
end
