# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waftester < Formula
  desc "WAF security testing CLI — detect, benchmark, and bypass web application firewalls"
  homepage "https://waftester.com"
  version "2.9.22"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waftester/waftester/releases/download/v2.9.22/waftester_Darwin_x86_64.tar.gz"
      sha256 "eb6dfb3d0b234be508b4a7d64460e4761e8fd6c50ccb0d3be20d573a4815775e"

      def install
        bin.install "waf-tester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waftester/waftester/releases/download/v2.9.22/waftester_Darwin_arm64.tar.gz"
      sha256 "5be46ea7c37cfcd0aa0ae0cf7f730bb7b79d60267e71bede431b4e9151550e59"

      def install
        bin.install "waf-tester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/waftester/waftester/releases/download/v2.9.22/waftester_Linux_x86_64.tar.gz"
      sha256 "bb4a9b09cf0e81c5dcc6adb61f980f5703cd6aa396b197203418243689dc6d44"
      def install
        bin.install "waf-tester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/waftester/waftester/releases/download/v2.9.22/waftester_Linux_arm64.tar.gz"
      sha256 "5da30a06a9ee729d4ccc06213d435243d4611fc934097bf419f102363bb25a1c"
      def install
        bin.install "waf-tester"
      end
    end
  end

  test do
    system "#{bin}/waf-tester", "version"
  end
end
